baseURL = "https://www.datavetenskap.nu/"
languageCode = "sv"
theme = "mainroad"
title = "Uppsala Datavetare"

# TODO: Language settings
defaultContentLanguage = 'sv'
[languages]
    [languages.sv]
        contentDir = 'content'
        languageName = 'Swedish'
        weight = 1
    [languages.sv.menu]
[[languages.sv.menu.main]]
    name = 'Hem'
    url = '/'
    weight = 1
[[languages.sv.menu.main]]
    name = 'Hem'
    url = '/'
    weight = 1

[Params]
description = "Uppsala Datavetare" # Site description. Used in meta description
#copyright = "John Doe" # Footer copyright holder, otherwise will use site title
authorbox = false # Show authorbox at bottom of pages if true
dateformat = "2006-01-02" # Change the format of dates
googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
mainSections = [
  "posts",
  "news",
] # Specify section pages to show on home page and the "Recent articles" widget     
mathjax = true # Enable MathJax
mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
opengraph = true # Enable OpenGraph if true
pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
post_meta = [
  "author",
  "date",
  "categories",
  "translations",
] # Order of post meta information     
readmore = true # Show "Read more" button in list if true
schema = true # Enable Schema
toc = true # Enable Table of Contents
twitter_cards = false # Enable Twitter Cards if true
# TODO: customCSS = ["css/custom.css"] # Include custom CSS files
# customJS = ["js/custom.js"] # Include custom JS files
# TODO: favicon = ""

[Params.style.vars]
  highlightColor = "#b22020" # Override highlight color

[Params.logo]
image = "img/patch.png" # Logo image. Path relative to "static"
subtitle = "Uppsala Datavetare" # Logo subtitle
title = "Uppsala Datavetare" # Logo title, otherwise will use site title

[Params.sidebar]
home = "right" # Configure layout for home page
list = "left" # Configure layout for list pages
single = false # Configure layout for single pages
# Enable widgets in given order
widgets = [
  "recent",
  "social",
  "categories",
  "taglist",
]
# alternatively "ddg-search" can be used, to search via DuckDuckGo
# widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
categories_counter = false # Enable counter for each category in "Categories" widget
recent_num = 5 # Set the number of articles in the "Recent articles" widget
tags_counter = false # Enable counter for each tag in "Tags" widget

[[Params.widgets.social.custom]]
  title = "Uppsala Datavetare"
  url = "https://www.facebook.com/SektionenUppsalaDatavetare"
  icon = "svg/facebook.svg"

[[Params.widgets.social.custom]]
  title = "Uppsala Datavetare"
  url = "https://www.instagram.com/uppsaladatavetare/"
  icon = "svg/instagram.svg"

[[Params.widgets.social.custom]]
  title = "DVKV"
  url = "https://www.facebook.com/DatavetenskapligaKV"
  icon = "svg/facebook.svg"

[[Params.widgets.social.custom]]
  title = "DVKV"
  url = "https://www.instagram.com/dvkv_uppsala"
  icon = "svg/instagram.svg"

[Params.widgets.social]
github = "uppsaladatavetare"
